const express = require('express');
const router = express.Router();
const {
  createBill,
  getOrdersByHotel,
  getHotelSummary,
  getCompletedBills,
  getEnhancedHotelSummary,
  getItemsAnalysis,
  getPaymentMethodBreakdown,
  getTopProducts,
  getRevenueByStaff,
  getHourlyTrends,
  getAdminStats,
  exportOrdersToExcel,
  deleteBill
} = require('../controllers/billController');

//  Bill Operations
router.post('/create', createBill);
router.get('/orders/:hotelId', getOrdersByHotel);
router.get('/export-orders/:hotelId', exportOrdersToExcel);
router.delete('/delete/:billId', deleteBill);

//  Admin Operations
router.get('/admin-stats/:hotelId/:adminId', getAdminStats);        // Admin billing statistics
router.get('/completed/:hotelId', getCompletedBills);

//  Analytics Routes
router.get('/report/:hotelId', getHotelSummary);                     // Daily/weekly/monthly summary
router.get('/enhanced-report/:hotelId', getEnhancedHotelSummary);    // Enhanced date range summary
router.get('/items-analysis/:hotelId', getItemsAnalysis);            // Detailed items analysis
router.get('/payment-summary/:hotelId', getPaymentMethodBreakdown); // Breakdown by payment type
router.get('/top-products/:hotelId', getTopProducts);               // Top 5 selling products
router.get('/staff-revenue/:hotelId', getRevenueByStaff);           // Revenue generated by each staff
router.get('/hourly-trends/:hotelId', getHourlyTrends);             // Hourly order trend

module.exports = router;
